// Sample data for testing
export const loadSampleData = () => {
  return [
    {
      id: "TICKET-001",
      title: "Implement user authentication",
      assignee: "Astandro",
      function: "BE",
      project: "Chatbot",
      status: "Closed",
      storyPoints: 8,
      sprintClosed: "Sprint 1",
      cycleDays: 5,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-01"),
      closedDate: new Date("2024-01-06")
    },
    {
      id: "TICKET-002", 
      title: "Fix login bug",
      assignee: "Astandro",
      function: "BE",
      project: "Chatbot",
      status: "Closed",
      storyPoints: 3,
      sprintClosed: "Sprint 1",
      cycleDays: 2,
      isBug: true,
      isRevise: false,
      createdDate: new Date("2024-01-07"),
      closedDate: new Date("2024-01-09")
    },
    {
      id: "TICKET-003",
      title: "Design user interface",
      assignee: "Sarah",
      function: "FE", 
      project: "Orion",
      status: "Closed",
      storyPoints: 5,
      sprintClosed: "Sprint 1",
      cycleDays: 4,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-02"),
      closedDate: new Date("2024-01-06")
    },
    {
      id: "TICKET-004",
      title: "Update dashboard layout",
      assignee: "Sarah",
      function: "FE",
      project: "Orion", 
      status: "Closed",
      storyPoints: 3,
      sprintClosed: "Sprint 2",
      cycleDays: 3,
      isBug: false,
      isRevise: true,
      createdDate: new Date("2024-01-10"),
      closedDate: new Date("2024-01-13")
    },
    {
      id: "TICKET-005",
      title: "Write unit tests",
      assignee: "Mike",
      function: "QA",
      project: "Xelvate",
      status: "Closed", 
      storyPoints: 6,
      sprintClosed: "Sprint 1",
      cycleDays: 4,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-03"),
      closedDate: new Date("2024-01-07")
    },
    {
      id: "TICKET-006",
      title: "Performance optimization",
      assignee: "Astandro",
      function: "BE",
      project: "Chatbot",
      status: "Closed",
      storyPoints: 13,
      sprintClosed: "Sprint 2", 
      cycleDays: 7,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-14"),
      closedDate: new Date("2024-01-21")
    },
    {
      id: "TICKET-007",
      title: "Mobile responsive design",
      assignee: "Sarah",
      function: "FE",
      project: "Orion",
      status: "Closed",
      storyPoints: 8,
      sprintClosed: "Sprint 2",
      cycleDays: 5,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-15"),
      closedDate: new Date("2024-01-20")
    },
    {
      id: "TICKET-008",
      title: "Database migration",
      assignee: "Astandro", 
      function: "BE",
      project: "Xelvate",
      status: "Closed",
      storyPoints: 21,
      sprintClosed: "Sprint 3",
      cycleDays: 10,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-22"),
      closedDate: new Date("2024-02-01")
    },
    {
      id: "TICKET-009",
      title: "API documentation",
      assignee: "Mike",
      function: "QA",
      project: "Chatbot",
      status: "Closed",
      storyPoints: 5,
      sprintClosed: "Sprint 3",
      cycleDays: 3,
      isBug: false,
      isRevise: false,
      createdDate: new Date("2024-01-25"),
      closedDate: new Date("2024-01-28")
    },
    {
      id: "TICKET-010",
      title: "Fix responsive issues",
      assignee: "Sarah",
      function: "FE",
      project: "Orion",
      status: "Closed",
      storyPoints: 2,
      sprintClosed: "Sprint 3",
      cycleDays: 1,
      isBug: true,
      isRevise: false,
      createdDate: new Date("2024-01-29"),
      closedDate: new Date("2024-01-30")
    }
  ];
};
