version: '3.8'

services:
  teamlight-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=3001
      
      # Authentication Credentials (CHANGE THESE FOR PRODUCTION!)
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin124$}
      - USER_USERNAME=${USER_USERNAME:-user}
      - USER_PASSWORD=${USER_PASSWORD:-user}
      
      # JWT Secret (CHANGE THIS FOR PRODUCTION!)
      - JWT_SECRET=${JWT_SECRET:-teamlight_secret_key_2024_production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - teamlight-network

networks:
  teamlight-network:
    driver: bridge
